# Generated by Django 4.2.11 on 2024-04-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_custumer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
