# Generated by Django 4.2.11 on 2024-05-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_quatity_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custemer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oder',
            new_name='order',
        ),
    ]
